# Generated by Django 5.2 on 2025-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checksheet1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
