# Generated by Django 5.2 on 2025-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checksheet1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checksheet",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AddField(
            model_name="checksheet",
            name="display_order",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
