# Generated by Django 5.2 on 2025-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checksheet1", "0002_productiontarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
